name: docker-manifest-create-action
description: Create a multi-architecture Docker image in GitHub Actions

inputs:
  tags:
    description: Tags of destination images (multi-line string)
    required: true
  sources:
    description: Image URIs of sources (multi-line string)
    required: true

outputs:
  digest:
    description: Digest of the created manifest

runs:
  using: 'node20'
  main: 'dist/index.js'
