name: docker-manifest-create-action
description: Create a multi-architecture Docker image in GitHub Actions

inputs:
  push:
    description: Push the manifest to the registry
    required: false
    default: 'true'
  annotations:
    description: Add annotations to the image index (multi-line string)
    required: false
  tags:
    description: Tags of the destination images (multi-line string)
    required: false
  sources:
    description: Image URIs of the sources (multi-line string)
    required: true

outputs:
  digest:
    description: Digest of the created manifest

runs:
  using: 'node20'
  main: 'dist/index.js'
