name: docker-manifest-create-action
description: Create a multi-architecture Docker image in GitHub Actions

inputs:
  tags:
    description: tags of destination images (multi-line string)
    required: true
  suffixes:
    description: suffixes of source images (multi-line string)
    required: true
  builder:
    description: builder (auto | buildx | docker)
    required: true
    default: auto

runs:
  using: 'node16'
  main: 'dist/index.js'
