name: docker-manifest-create-action
description: Create a multi-architecture Docker image in GitHub Actions

inputs:
  tags:
    description: tags of destination images (multi-line string)
    required: true
  suffixes:
    description: suffixes of source images (multi-line string)
    required: true
  use-buildx:
    description: use docker buildx (auto | true | false)
    required: false
    default: auto

runs:
  using: 'node16'
  main: 'dist/index.js'
