name: e2e-kaniko

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/e2e-kaniko.yaml
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/e2e-kaniko.yaml

jobs:
  # Skip the build if triggered by a forked repository, because it cannot push the image to the registry.
  skip-if-fork:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-slim
    steps:
      - run: exit 0

  build-linux-amd64:
    needs: skip-if-fork
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image-uri: ghcr.io/${{ github.repository }}/e2e@${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/e2e
          # avoid overwriting the latest tag because metadata-action does not add a suffix to it
          flavor: latest=false,suffix=-kaniko-amd64
      - uses: int128/kaniko-action@a0a6dbfbc587c46807c6367bc0118f01edd11764 # v1.64.0
        id: build
        with:
          push: true
          context: tests/fixtures
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  build:
    needs:
      - build-linux-amd64
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image-uri: ghcr.io/${{ github.repository }}/e2e@${{ steps.build.outputs.digest }}
    steps:
      # build the action
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm build

      # run the action
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/e2e
          flavor: latest=false,suffix=-kaniko
      - name: docker-manifest-create-action (dry-run)
        uses: ./
        with:
          push: false
          index-annotations: ${{ steps.metadata.outputs.labels }}
          sources: |
            ${{ needs.build-linux-amd64.outputs.image-uri }}

      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker-manifest-create-action@v2
        id: build
        uses: ./
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ${{ needs.build-linux-amd64.outputs.image-uri }}

  test-image:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run --rm '${{ needs.build.outputs.image-uri }}'
