name: docker-build

on:
  workflow_call:
    inputs:
      images:
        description: Passed to docker/metadata-action
        type: string
        required: true
      cache-image:
        description: Passed to int128/docker-build-cache-config-action
        type: string
        required: true
      context:
        description: Passed to docker/build-push-action
        type: string
        required: true
      platforms:
        description: Passed to docker/build-push-action
        type: string
        required: true
    outputs:
      image-uri:
        description: Image URI
        value: ${{ jobs.build.outputs.image-uri }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image-uri: ghcr.io/${{ github.repository }}/e2e@${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          images: ${{ inputs.images }}
          # avoid overwriting the latest tag because metadata-action does not add a suffix to it
          flavor: latest=false,suffix=-amd64
      - uses: int128/docker-build-cache-config-action@d1b27ffbf29fb93b7239130db030c702198fd52b # v1.64.0
        id: cache
        with:
          image: ${{ inputs.cache-image }}
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: build
        with:
          push: true
          context: ${{ inputs.context }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          platforms: ${{ inputs.platforms }}
